format_version: 10
pipelines:
  code-pipeline-test:
    group: CRA-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@github.com:akprasad-cs/gocd-cra.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - code-stage-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          install:
            timeout: 0
            elastic_profile_id: k8s-cluster-profile
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
            - script: |
                echo "username: ${DOCKERHUB_USERNAME}"
